name: Playwright Visual Tests

run-name: >
  Visual Regression |
  ${{ github.event_name }} |
  ${{ github.actor }}

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  visual-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Visual Tests
        run: npx playwright test --grep @visual --update-snapshots

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: visual-playwright-report
          path: playwright-report/

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report
          path: allure-report/

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v3
        if: always()
        with:
          path: allure-report/
           

  deploy:
    if: always()

    needs: 
      - visual-tests
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Add Report Link To Summary
        run: |
          echo "## Hosted Allure Report" >> $GITHUB_STEP_SUMMARY
          echo "${{ steps.deployment.outputs.page_url }}" >> $GITHUB_STEP_SUMMARY

      - name: Slack Success Notification - Basic 
        if: needs.visual-tests.result == 'success'
        run: |
          curl -X POST \
            -H 'Content-type: application/json' \
            --data "{
              \"text\": \"✅ Playwright Pipeline PASSED

              🌿 Branch:
              ${{ github.ref_name }}

              👤 Triggered By:
              ${{ github.actor }}

              📊 Hosted Report:
              ${{ steps.deployment.outputs.page_url }}

              🚀 Workflow:
              ${{ github.workflow }}\"
             }" \
            ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Slack Failure Notification - Basic
        if: needs.visual-tests.result == 'failure'
        run: |
          curl -X POST \
            -H 'Content-type: application/json' \
            --data "{
              \"text\": \"❌ Playwright Pipeline FAILED

              🌿 Branch:
              ${{ github.ref_name }}

              👤 Triggered By:
              ${{ github.actor }}

              📊 Hosted Report:
              ${{ steps.deployment.outputs.page_url }}

              ⚠️ Check GitHub Actions logs immediately.\"
             }" \
            ${{ secrets.SLACK_WEBHOOK_URL }}

